### PR TITLE
Make url configurable on the command call

### PR DESCRIPTION
**Pull request by jmcs**

### CODE REVIEW

**Comment by prayerslayer** [comment]
What is the use case for this? It makes sense in pierone-cli as we have two of them, but there is only one Kio.

**Comment by jmcs** [comment]
I need to use kio from [lizzy](https://github.com/zalando/lizzy). I want to make the url configurable with an environmental variable, and I would prefer not having to write a config file on startup, with this option I can just pass the URL in every call.

**Comment by prayerslayer** [comment]
Hmm to me that sounds like a special use case where you already have a solution to (`echo "{ url: <kio url> }" > ~/.config/kio.yaml`) but very few other people would benefit from it. I'd rather not introduce that change, but I'm not the maintainer, so don't listen to me.

**Comment by hjacobs** [comment]
@jmcs I agree with @prayerslayer, but I propose an alternative: we can make the config loading generic to consider environment variables too

**Comment by hjacobs** [comment]
@jmcs https://github.com/zalando-stups/stups-cli-support/issues/3

**Comment by hjacobs** [comment]
Changed the stups-cli-support to allow overwritting via ENV vars.

**Pull request closed without merging**
